"""Initial monitoring schema with daily GPU sample partitions."""

from alembic import op

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


SCHEMA_SQL = r"""
SET TIME ZONE 'UTC';

CREATE SCHEMA IF NOT EXISTS partman;
CREATE EXTENSION IF NOT EXISTS pg_partman SCHEMA partman;

CREATE TABLE admins (
    id uuid PRIMARY KEY,
    username varchar(100) NOT NULL UNIQUE,
    password_hash text NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);

CREATE TABLE admin_sessions (
    id uuid PRIMARY KEY,
    admin_id uuid NOT NULL REFERENCES admins(id) ON DELETE CASCADE,
    token_hash bytea NOT NULL UNIQUE,
    csrf_hash bytea NOT NULL,
    expires_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL
);
CREATE INDEX ix_admin_sessions_expires_at ON admin_sessions(expires_at);

CREATE TABLE compute_resources (
    id uuid PRIMARY KEY,
    name varchar(200) NOT NULL,
    gpu_model varchar(200) NOT NULL,
    gpu_count integer NOT NULL CHECK (gpu_count > 0),
    token_hash bytea NOT NULL UNIQUE,
    token varchar(100) NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    archived_at timestamptz
);
CREATE UNIQUE INDEX uq_compute_resources_active_name
    ON compute_resources(name) WHERE archived_at IS NULL;

CREATE TABLE container_instances (
    id uuid PRIMARY KEY,
    resource_id uuid NOT NULL REFERENCES compute_resources(id) ON DELETE RESTRICT,
    name varchar(255) NOT NULL,
    generation integer NOT NULL,
    first_reported_at timestamptz NOT NULL,
    last_received_at timestamptz NOT NULL,
    latest_collected_at timestamptz NOT NULL,
    current_gpu_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
    removed_at timestamptz,
    CONSTRAINT uq_container_generation UNIQUE(resource_id, name, generation)
);
CREATE UNIQUE INDEX uq_container_active_name
    ON container_instances(resource_id, name) WHERE removed_at IS NULL;
CREATE INDEX ix_container_resource_active
    ON container_instances(resource_id, removed_at);

CREATE TABLE sample_batches (
    id uuid NOT NULL,
    container_id uuid NOT NULL REFERENCES container_instances(id) ON DELETE RESTRICT,
    collected_at timestamptz NOT NULL,
    received_at timestamptz NOT NULL,
    payload_hash bytea NOT NULL,
    PRIMARY KEY(id, collected_at),
    CONSTRAINT uq_batch_container_collected UNIQUE(container_id, collected_at)
) PARTITION BY RANGE(collected_at);

CREATE TABLE gpu_samples (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    collected_at timestamptz NOT NULL,
    received_at timestamptz NOT NULL,
    batch_id uuid NOT NULL,
    resource_id uuid NOT NULL,
    container_id uuid NOT NULL,
    gpuid varchar(160) NOT NULL,
    memory_used bigint NOT NULL CHECK (memory_used >= 0 AND memory_used <= memory_total),
    memory_total bigint NOT NULL CHECK (memory_total > 0),
    utilization integer NOT NULL CHECK (utilization >= 0 AND utilization <= 100),
    PRIMARY KEY(id, collected_at),
    CONSTRAINT uq_gpu_sample_identity UNIQUE(container_id, gpuid, collected_at)
) PARTITION BY RANGE(collected_at);

CREATE INDEX ix_gpu_samples_container_time ON gpu_samples(container_id, collected_at);
CREATE INDEX ix_gpu_samples_resource_time ON gpu_samples(resource_id, collected_at);

SELECT partman.create_partition(
    p_parent_table := 'public.sample_batches',
    p_control := 'collected_at',
    p_interval := '1 day',
    p_premake := 7,
    p_jobmon := false
);

SELECT partman.create_partition(
    p_parent_table := 'public.gpu_samples',
    p_control := 'collected_at',
    p_interval := '1 day',
    p_premake := 7,
    p_jobmon := false
);

UPDATE partman.part_config
SET retention = '30 days',
    retention_keep_table = false,
    retention_keep_index = false,
    infinite_time_partitions = true,
    automatic_maintenance = 'on'
WHERE parent_table IN ('public.sample_batches', 'public.gpu_samples');
"""


def upgrade() -> None:
    op.execute(SCHEMA_SQL)


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS gpu_samples CASCADE")
    op.execute("DROP TABLE IF EXISTS sample_batches CASCADE")
    op.execute("DROP TABLE IF EXISTS container_instances CASCADE")
    op.execute("DROP TABLE IF EXISTS compute_resources CASCADE")
    op.execute("DROP TABLE IF EXISTS admin_sessions CASCADE")
    op.execute("DROP TABLE IF EXISTS admins CASCADE")
